"""
Gmail delivery — sends a notification email with the weekly pulse summary.

Uses the Gmail API (v1) with OAuth credentials from gcp_token.json.
"""

from __future__ import annotations

import base64
import json
import logging
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import List, Optional

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

from review_pulse.store.models import AnalysisResult

logger = logging.getLogger(__name__)

SCOPES = [
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/gmail.compose",
]


def _get_credentials() -> Credentials:
    """Load and refresh OAuth credentials from gcp_token.json."""
    token_path = os.environ.get(
        "GOOGLE_OAUTH_TOKEN_PATH",
        str(Path(__file__).resolve().parents[3] / "gcp_token.json"),
    )

    if not Path(token_path).exists():
        raise FileNotFoundError(
            f"gcp_token.json not found at {token_path}. "
            "Run `python generate_token.py` to create it."
        )

    creds = Credentials.from_authorized_user_file(token_path, SCOPES)

    if creds.expired and creds.refresh_token:
        logger.info("🔄 Refreshing expired Google OAuth token...")
        creds.refresh(Request())
        Path(token_path).write_text(creds.to_json())

    return creds


def _build_html_body(
    product: str,
    iso_week: str,
    analysis: AnalysisResult,
    doc_id: Optional[str] = None,
) -> str:
    """Build a clean HTML email body summarising the weekly pulse."""
    doc_url = f"https://docs.google.com/document/d/{doc_id}" if doc_id else "#"

    themes_html = ""
    for i, theme in enumerate(analysis.themes, 1):
        quotes_html = ""
        for q in theme.quotes:
            quotes_html += f'<li><em>"{q.text}"</em> — ★{q.rating} ({q.store})</li>\n'

        themes_html += f"""
        <div style="margin-bottom: 20px; padding: 16px; border-left: 4px solid #4285f4; background: #f8f9fa;">
            <h3 style="margin: 0 0 8px 0; color: #1a73e8;">Theme {i}: {theme.name}</h3>
            <p style="margin: 4px 0; color: #5f6368;">{theme.description}</p>
            <p style="margin: 4px 0;"><strong>Reviews:</strong> {theme.review_count}</p>
            {f'<ul style="margin: 8px 0;">{quotes_html}</ul>' if quotes_html else ''}
            {f'<p style="margin: 4px 0;"><strong>✅ Action:</strong> {theme.action}</p>' if theme.action else ''}
        </div>
        """

    html = f"""
    <html>
    <body style="font-family: 'Google Sans', Arial, sans-serif; max-width: 680px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #1a73e8, #4285f4); padding: 24px; border-radius: 12px; color: white; margin-bottom: 24px;">
            <h1 style="margin: 0; font-size: 24px;">📊 Weekly Review Pulse</h1>
            <p style="margin: 8px 0 0 0; font-size: 16px; opacity: 0.9;">{product.title()} — {iso_week}</p>
        </div>

        <div style="display: flex; gap: 12px; margin-bottom: 24px;">
            <div style="flex: 1; background: #e8f0fe; padding: 12px; border-radius: 8px; text-align: center;">
                <div style="font-size: 24px; font-weight: bold; color: #1a73e8;">{analysis.total_reviews}</div>
                <div style="font-size: 12px; color: #5f6368;">Reviews</div>
            </div>
            <div style="flex: 1; background: #e6f4ea; padding: 12px; border-radius: 8px; text-align: center;">
                <div style="font-size: 24px; font-weight: bold; color: #1e8e3e;">{len(analysis.themes)}</div>
                <div style="font-size: 12px; color: #5f6368;">Themes</div>
            </div>
            <div style="flex: 1; background: #fce8e6; padding: 12px; border-radius: 8px; text-align: center;">
                <div style="font-size: 24px; font-weight: bold; color: #d93025;">{analysis.tokens_used:,}</div>
                <div style="font-size: 12px; color: #5f6368;">Tokens</div>
            </div>
        </div>

        <h2 style="color: #202124; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px;">🔍 Key Themes</h2>

        {themes_html}

        <div style="margin-top: 24px; padding: 16px; background: #e8f0fe; border-radius: 8px; text-align: center;">
            <a href="{doc_url}" style="color: #1a73e8; font-weight: bold; font-size: 16px; text-decoration: none;">
                📄 View Full Report in Google Docs →
            </a>
        </div>

        <p style="margin-top: 24px; font-size: 12px; color: #9aa0a6; text-align: center;">
            Generated by Review Pulse AI Agent • Powered by Groq + Gemini
        </p>
    </body>
    </html>
    """
    return html


def send_gmail_notification(
    product: str,
    iso_week: str,
    analysis: AnalysisResult,
    recipients: List[str],
    doc_id: Optional[str] = None,
) -> Optional[str]:
    """
    Send a Gmail notification with the weekly pulse summary.

    Args:
        product: Product name.
        iso_week: ISO week string.
        analysis: The analysis result to summarise.
        recipients: List of email addresses to notify.
        doc_id: Optional Google Doc ID to link in the email.

    Returns:
        Gmail message ID, or None if delivery was skipped/failed.
    """
    if not recipients:
        logger.info("📧 No recipients configured — skipping Gmail notification")
        return None

    creds = _get_credentials()
    service = build("gmail", "v1", credentials=creds)

    # Get sender email from the authenticated user
    profile = service.users().getProfile(userId="me").execute()
    sender = profile["emailAddress"]

    subject = f"📊 Review Pulse — {product.title()} — {iso_week}"
    html_body = _build_html_body(product, iso_week, analysis, doc_id)

    # Build MIME message
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = ", ".join(recipients)

    # Plain text fallback
    plain_text = f"Weekly Review Pulse for {product.title()} ({iso_week})\n\n"
    plain_text += f"Reviews: {analysis.total_reviews} | Themes: {len(analysis.themes)}\n\n"
    for i, theme in enumerate(analysis.themes, 1):
        plain_text += f"{i}. {theme.name}: {theme.description}\n"
        if theme.action:
            plain_text += f"   Action: {theme.action}\n"
    if doc_id:
        plain_text += f"\nFull report: https://docs.google.com/document/d/{doc_id}\n"

    msg.attach(MIMEText(plain_text, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    # Encode and send
    raw_message = base64.urlsafe_b64encode(msg.as_bytes()).decode("utf-8")

    try:
        result = service.users().messages().send(
            userId="me",
            body={"raw": raw_message},
        ).execute()
        msg_id = result.get("id", "unknown")
        logger.info("📧 Gmail sent to %s (msg_id=%s)", recipients, msg_id)
        return msg_id
    except Exception as e:
        logger.error("📧 Gmail send failed: %s", e)
        return None
